import type { Metadata } from "next";
import LegalLayout from "@/components/ui/LegalLayout";

export const metadata: Metadata = {
  title: "Privacy Policy — Digital Doorstep",
  description: "Privacy Policy for Digital Doorstep Web Design in Noblesville, Indiana.",
  robots: { index: false, follow: false },
};

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="June 1, 2025">

      <p>This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Service, and tells you about your privacy rights and how the law protects you.</p>
      <p>We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.</p>

      <h2>Interpretation and Definitions</h2>

      <h3>Interpretation</h3>
      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &ldquo;control&rdquo; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo;, or &ldquo;Our&rdquo; in this Agreement) refers to Digital Doorstep Web Design, 11119 Giddings Place, Noblesville, IN 46060.</li>
        <li><strong>Cookies</strong> are small files placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: Indiana, United States.</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to Digital Doorstep Web Design, accessible from <a href="https://digitaldoorstep.net">https://digitaldoorstep.net</a>.</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>

      <h3>Types of Data Collected</h3>

      <h4>Personal Data</h4>
      <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>

      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>Usage Data may include information such as your device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>
      <p>When you access the Service by or through a mobile device, we may collect certain information automatically, including but not limited to the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers, and other diagnostic data.</p>
      <p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device.</p>

      <h4>Tracking Technologies and Cookies</h4>
      <p>We use Cookies and similar tracking technologies to track the activity on our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. The technologies we use may include:</p>
      <ul>
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on your device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our Service. Unless you have adjusted your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email, and for other related website statistics.</li>
      </ul>
      <p>Cookies can be &ldquo;Persistent&rdquo; or &ldquo;Session&rdquo; Cookies. Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser.</p>
      <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul>
        <li>
          <strong>Necessary / Essential Cookies</strong><br />
          Type: Session Cookies &mdash; Administered by: Us<br />
          Purpose: These Cookies are essential to provide you with services available through the Website and to enable you to use some of its features. Without these Cookies, the services that you have asked for cannot be provided.
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong><br />
          Type: Persistent Cookies &mdash; Administered by: Us<br />
          Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
        </li>
        <li>
          <strong>Functionality Cookies</strong><br />
          Type: Persistent Cookies &mdash; Administered by: Us<br />
          Purpose: These Cookies allow us to remember choices you make when you use the Website, such as remembering your login details or language preference.
        </li>
      </ul>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage your Account:</strong> to manage your registration as a user of the Service.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or of any other contract with us through the Service.</li>
        <li><strong>To contact you:</strong> by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products, or contracted services.</li>
        <li><strong>To provide you</strong> with news, special offers, and general information about other goods, services, and events we offer that are similar to those you have already purchased or enquired about, unless you have opted not to receive such information.</li>
        <li><strong>To manage your requests:</strong> to attend and manage your requests to us.</li>
        <li><strong>For business transfers:</strong> we may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets.</li>
        <li><strong>For other purposes:</strong> such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service.</li>
      </ul>
      <p>We may share your personal information in the following situations:</p>
      <ul>
        <li><strong>With Service Providers:</strong> we may share your personal information with Service Providers to monitor and analyze the use of our Service.</li>
        <li><strong>For business transfers:</strong> we may share or transfer your personal information in connection with any merger, sale of Company assets, financing, or acquisition.</li>
        <li><strong>With Affiliates:</strong> we may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
        <li><strong>With business partners:</strong> we may share your information with our business partners to offer you certain products, services, or promotions.</li>
        <li><strong>With your consent:</strong> we may disclose your personal information for any other purpose with your consent.</li>
      </ul>

      <h3>Retention of Your Personal Data</h3>
      <p>The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
      <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

      <h3>Transfer of Your Personal Data</h3>
      <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those in your jurisdiction.</p>
      <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
      <p>The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organization or country unless there are adequate controls in place.</p>

      <h3>Delete Your Personal Data</h3>
      <p>You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you. You may contact us to request access to, correct, or delete any personal information that you have provided to us.</p>
      <p>Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

      <h3>Disclosure of Your Personal Data</h3>

      <h4>Business Transactions</h4>
      <p>If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

      <h4>Law Enforcement</h4>
      <p>Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

      <h4>Other Legal Requirements</h4>
      <p>The Company may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h3>Security of Your Personal Data</h3>
      <p>The security of your Personal Data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

      <h2>Children&apos;s Privacy</h2>
      <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.</p>

      <h2>Links to Other Websites</h2>
      <p>Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
      <p>We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

      <h2>Changes to This Privacy Policy</h2>
      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &ldquo;Last updated&rdquo; date at the top of this Privacy Policy.</p>
      <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, you can contact us:</p>
      <ul>
        <li>By email: <a href="mailto:jhepworth@digitaldoorstep.net">jhepworth@digitaldoorstep.net</a></li>
        <li>By visiting our contact page: <a href="/#contact">digitaldoorstep.net/#contact</a></li>
      </ul>

    </LegalLayout>
  );
}
